### PR TITLE
Add minimal gcloud dependency and bump version number (hoping to fix weird errors)

### PR DESCRIPTION
**Pull request by andymutton**

### CODE REVIEW

**Comment by andymutton** [comment]
LGTM ANDY!

**Comment by andymutton** [comment]
Oh, sweet. Thanks! I'll just merge it then.

**Comment by nainar** [comment]
I see no problem with this change and exchange. I heartily agree with Andy's LGTM of Andy's patch!

**Comment by sbermeister** [comment]
Not LGTM

**Comment by andymutton** [comment]
Hey! It is flawless! FLAWLESS!

**Comment by shans** [comment]
IT LOOKS LIKE CODE TO ME

**Comment by shans** [comment]
(MATT DAAAAAMON)

**Pull request merged**
